# Generated by Django 4.2 on 2023-04-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customer_created_at_alter_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='sent_times',
            field=models.IntegerField(default=0),
        ),
    ]
