# Generated by Django 4.2 on 2023-04-26 17:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_invoice_sent_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='billing_address',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='shipping_address',
            field=models.TextField(default='sadsada'),
            preserve_default=False,
        ),
    ]
