# Generated by Django 4.2 on 2023-04-27 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_customer_billing_address_customer_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='paymnet_status',
            field=models.CharField(choices=[('paid', 'PAID'), ('unpaid', 'UNPAID')], default=('paid', 'PAID'), max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.customer'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('completed', 'Completed')], default=('active', 'Active'), max_length=10),
        ),
    ]
